const gardenwoodland = [
  
{english: "Gorgeous Bushshrike", afrikaans: "Konkoit", hotspot: "St Lucia; Kruger National Park; Limpopo; KZN; Mpumalanga", habitat: "Woodland; Forest", birdgroup: "Garden and Woodland", level: "1 Beginner", 
 audio: "gardenwoodland/XC1100369_GorgeousBushshrike.mp3", spectrogram: "gardenwoodland/XC1100369_GorgeousBushshrike.png",image: "gardenwoodland/XC1100369_GorgeousBushshrike.jpg", photographer: "Marna Buys", credit: "© Marna Buys, www.xeno-canto.org, XC1100369, Background birds: emerald-spotted wood dove, grey-headed bushshrike, ring-necked dove, etc", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Blue-mantled Crested Flycatcher", afrikaans: "Bloukuifvlieëvanger", hotspot: "Western Cape; Eastern Cape, KZN; Mpumalanga", habitat: "Forest", birdgroup: "Garden and Woodland", level: "3 Advanced", 
  audio: "gardenwoodland/XC1100676_Blue-mantledCrestedFlycatcher.mp3", spectrogram: "gardenwoodland/XC1100676_Blue-mantledCrestedFlycatcher.png",image: "gardenwoodland/XC1100676_Blue-mantledCrestedFlycatcher.jpg", photographer: "Marna Buys", credit: "© Marna Buys, www.xeno-canto.org, XC1100676", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Woodwards Batis", afrikaans: "Woodwardbosbontrokkie", hotspot: "KZN; St Lucia", habitat: "Forest", birdgroup: "Garden and Woodland", level: "2 Intermediate", 
audio: "gardenwoodland/XC1100685_WoodwardsBatis.mp3", spectrogram: "gardenwoodland/XC1100685_WoodwardsBatis.png",image: "gardenwoodland/XC1100685_WoodwardsBatis.jpg", photographer: "Marna Buys", credit: "© Marna Buys, www.xeno-canto.org, XC1100685", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Broad-billed Roller", afrikaans: "Geelbektroupant", hotspot: "KZN; Limpopo; Mpumalanga", habitat: "Grassland; Forest", birdgroup: "Garden and Woodland", level: "2 Intermediate", 
audio: "gardenwoodland/XC398047_Broad-billedRoller.mp3", spectrogram: "gardenwoodland/XC398047_Broad-billedRoller.png",image: "gardenwoodland/XC398047_Broad-billedRoller.jpg", photographer: "Marna Buys", credit: "© Peter Boesman, www.xeno-canto.org, XC398047", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Racket-tailed Roller", afrikaans: "Knopsterttroupant", hotspot: "Limpopo", habitat: "Woodland", birdgroup: "Garden and Woodland", level: "2 Intermediate", 
audio: "gardenwoodland/XC854403_Racket-tailedRoller.mp3", spectrogram: "gardenwoodland/XC854403_Racket-tailedRoller.png",image: "gardenwoodland/XC854403_Racket-tailedRoller.jpg", photographer: "Marna Buys", credit: "© Dries Van de Loock, www.xeno-canto.org, XC854403", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Lilac-breasted Roller", afrikaans: "Gewone Troupant", hotspot: "Gauteng; KZN; Mpumalanga; Limpopo; Nothern Cape", habitat: "Woodland", birdgroup: "Garden and Woodland", level: "2 Intermediate", 
audio: "gardenwoodland/XC510090_Lilac-breastedRoller.mp3", spectrogram: "gardenwoodland/XC510090_Lilac-breastedRoller.png",image: "gardenwoodland/XC510090_Lilac-breastedRoller.jpg", photographer: "Marna Buys", credit: "© Peter Boesman, www.xeno-canto.org, XC510090", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Purple Roller", afrikaans: "Groottroupant", hotspot: "Northwest; Mpumalanga; Limpopo", habitat: "Woodland", birdgroup: "Garden and Woodland", level: "2 Intermediate", 
audio: "gardenwoodland/XC719046_PurpleRoller.mp3", spectrogram: "gardenwoodland/XC719046_PurpleRoller.png",image: "gardenwoodland/XC719046_PurpleRoller.jpg", photographer: "Marna Buys", credit: "© Peter Boesman, www.xeno-canto.org, XC719046", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Green malkoha", afrikaans: "Groenvleiloerie", hotspot: "St Lucia", habitat: "Forest", birdgroup: "Garden and Woodland", level: "2 Intermediate", 
audio: "gardenwoodland/XC279998_GreenMalkoha.mp3", spectrogram: "gardenwoodland/XC279998_GreenMalkoha.png",image: "gardenwoodland/XC279998_GreenMalkoha.jpg", photographer: "Marna Buys", credit: "© Peter Boesman, www.xeno-canto.org, XC279998", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Livingstons Turaco", afrikaans: "Mosambiekloerie", hotspot: "St Lucia", habitat: "Forest", birdgroup: "Garden and Woodland", level: "1 Beginner", 
audio: "gardenwoodland/XC280730_LivingstonesTuraco.mp3", spectrogram: "gardenwoodland/XC280730_LivingstonesTuraco.png",image: "gardenwoodland/XC280730_LivingstonesTuraco.jpg", photographer: "Marna Buys", credit: "© Peter Boesman, www.xeno-canto.org, XC280730", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Karoo Scrub-Robin", afrikaans: "Slangverklikker", hotspot: "Platbakkies", habitat: "Fynbos", birdgroup: "Garden and Woodland", level: "3 Advanced", 
audio: "gardenwoodland/XC714080_KarooScrubRobin.mp3", spectrogram: "gardenwoodland/XC714080_KarooScrubRobin.png",image: "gardenwoodland/XC714080_KarooScrubRobin.jpg", photographer: "Marna Buys", credit: "© Tim Cockrcroft, www.xeno-canto.org, XC714080", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Grey Tit", afrikaans: "Piet-Tjou-Tjou-grysmees", hotspot: "Platbakkies", habitat: "Shrubland", birdgroup: "Garden and Woodland", level: "2 Intermediate", 
audio: "gardenwoodland/XC610170_GreyTit.mp3", spectrogram: "gardenwoodland/XC610170_GreyTit.png",image: "gardenwoodland/XC610170_GreyTit.jpg", photographer: "Marna Buys", credit: "© Lynette Rudman, www.xeno-canto.org, XC610170", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "White-throated Robin-chat contact call", afrikaans: "Witkeeljanfrederik kontak", hotspot: "Zaagkuildrift", habitat: "Woodland", birdgroup: "Garden and Woodland", level: "2 Intermediate", 
audio: "gardenwoodland/XC1102351_White-throatedRobin-Chat.mp3", spectrogram: "gardenwoodland/XC1102351_White-throatedRobin-Chat.png",image: "gardenwoodland/XC1102351_White-throatedRobin-Chat.jpg", photographer: "Marna Buys", credit: "© Marna Buys, www.xeno-canto.org, XC1102351", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Cape Robin-Chat", afrikaans: "Gewone Janfrederik", hotspot: "Zaagkuildrift", habitat: "Woodland", birdgroup: "Garden and Woodland", level: "1 Beginner", 
audio: "gardenwoodland/XC1067750_CapeRobin-Chat.mp3", spectrogram: "gardenwoodland/XC1067750_CapeRobin-Chat.png",image: "gardenwoodland/XC1067750_CapeRobin-Chat.jpg", photographer: "Marna Buys", credit: "© Nature sounds by Simply Birding, www.xeno-canto.org, XC1067750", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "White-throated Robin-chat song", afrikaans: "Witkeeljanfrederik sang", hotspot: "Zaagkuildrift", habitat: "Woodland", birdgroup: "Garden and Woodland", level: "3 Advanced", 
audio: "gardenwoodland/XC1102359_White-throatedRobin-Chat.mp3", spectrogram: "gardenwoodland/XC1102359_White-throatedRobin-Chat.png",image: "gardenwoodland/XC1102359_White-throatedRobin-Chat.jpg", photographer: "Marna Buys", credit: "© Marna Buys, www.xeno-canto.org, XC1102359", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "White-browed Robin-chat", afrikaans: "Heuglinjanfrederik", hotspot: "Kruger National Park", habitat: "Woodland", birdgroup: "Garden and Woodland", level: "2 Intermediate", 
audio: "gardenwoodland/XC949507_White-browedRobin-Chat.mp3", spectrogram: "gardenwoodland/XC949507_White-browedRobin-Chat.png",image: "gardenwoodland/XC949507_White-browedRobin-Chat.jpg", photographer: "Marna Buys", credit: "© Bram Piot, www.xeno-canto.org, XC949507", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Yellow-breasted Apalis", afrikaans: "Geelborskleinjantjie", hotspot: "Kruger National Park", habitat: "Woodland", birdgroup: "Garden and Woodland", level: "2 Intermediate", audio: "gardenwoodland/XC878065_Yellow-breastedApalis.mp3", spectrogram: "gardenwoodland/XC878065_Yellow-breastedApalis.png",image: "gardenwoodland/XC878065_Yellow-breastedApalis.jpg", photographer: "Marna Buys", credit: "© Marc Anderson, www.xeno-canto.org, XC878065", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Bar-throated Apalis", afrikaans: "Bandkeelkleinjantjie", hotspot: "Roodeplaat Nature Reserve", habitat: "Woodland", birdgroup: "Garden and Woodland", level: "1 Beginner", audio: "gardenwoodland/XC1102549_Bar-throatedApalis.mp3", spectrogram: "gardenwoodland/XC1102549_Bar-throatedApalis.png",image: "gardenwoodland/XC1102549_Bar-throatedApalis.jpg", photographer: "Marna Buys", credit: "© Marna Buys, www.xeno-canto.org, XC1102549", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Brown Scrub Robin", afrikaans: "Bruinwipstert", hotspot: "Isimangaliso; Magoebas/Soutpans-/Waterberg; Mpumalanga", habitat: "Forest; Garden", birdgroup: "Garden and Woodland", level: "3 Advanced", 
audio: "gardenwoodland/XC279972_BrownScrubRobin.mp3", spectrogram: "gardenwoodland/XC279972_BrownScrubRobin.png",image: "gardenwoodland/XC279972_BrownScrubRobin.jpg", photographer: "Marna Buys", credit: "© Peter Boesman, www.xeno-canto.org, XC279972", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Bearded Scrub Robin", afrikaans: "Baardwipstert", hotspot: "Isimangaliso; Magoebas/Soutpans-/Waterberg; Mpumalanga; Kruger NP Pafuri", habitat: "Woodland", birdgroup: "Garden and Woodland", level: "3 Advanced", 
audio: "gardenwoodland/XC948017_BeardedScrubRobin.mp3", spectrogram: "gardenwoodland/XC948017_BeardedScrubRobin.png",image: "gardenwoodland/XC948017_BeardedScrubRobin.jpg", photographer: "Marna Buys", credit: "© Peter Boesman, www.xeno-canto.org, XC948017", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Kalahari Scrub Robin", afrikaans: "Kalahariwipstert", hotspot: "General", habitat: "Woodland", birdgroup: "Garden and Woodland", level: "3 Advanced", 
audio: "gardenwoodland/XC695669_KalahariScrubRobin.mp3", spectrogram: "gardenwoodland/XC695669_KalahariScrubRobin.png",image: "gardenwoodland/XC695669_KalahariScrubRobin.jpg", photographer: "Marna Buys", credit: "© Tony Archer, www.xeno-canto.org, XC695669", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "White-browed Scrub Robin", afrikaans: "Gestreepte wipstert", hotspot: "General", habitat: "Woodland", birdgroup: "Garden and Woodland", level: "2 Intermediate", 
audio: "gardenwoodland/XC834106_White-browedScrubRobin.mp3", spectrogram: "gardenwoodland/XC834106_White-browedScrubRobin.png",image: "gardenwoodland/XC834106_White-browedScrubRobin.jpg", photographer: "Marna Buys", credit: "© Marc Anderson, www.xeno-canto.org, XC834106", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Arnot's Chat", afrikaans: "Bontpiek", hotspot: "Kruger NP Pafuri", habitat: "Woodland", birdgroup: "Garden and Woodland", level: "3 Advanced", 
audio: "gardenwoodland/XC398145_ArnotsChat.mp3", spectrogram: "gardenwoodland/XC398145_ArnotsChat.png",image: "gardenwoodland/XC398145_ArnotsChat.jpg", photographer: "Marna Buys", credit: "© Peter Boesman, www.xeno-canto.org, XC398145", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Common Sqaure-tailed Drongo", afrikaans: "Kleinbyvanger", hotspot: "Isimangaliso; Magoebas/Soutpans-/Waterberg; Mpumalanga", habitat: "Forest; Woodland", birdgroup: "Garden and Woodland", level: "3 Advanced", 
audio: "gardenwoodland/XC652469_CommonSquare-tailedDrongo.mp3", spectrogram: "gardenwoodland/XC652469_CommonSquare-tailedDrongo.png",image: "gardenwoodland/XC652469_CommonSquare-tailedDrongo.jpg", photographer: "Marna Buys", credit: "© Niall Perrins, www.xeno-canto.org, XC652469", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Red-capped Robin-Chat song & immitation", afrikaans: "Nataljanfrederik sing & mimiek", hotspot: "Isimangaliso; Magoebas/Soutpans-/Waterberg; Mpumalanga; Kruger NP Pafuri", habitat: "Forest; Woodland", birdgroup: "Garden and Woodland", level: "3 Advanced", 
audio: "gardenwoodland/XC280179_Red-cappedRobin-Chat.mp3", spectrogram: "gardenwoodland/XC280179_Red-cappedRobin-Chat.png",image: "gardenwoodland/XC280179_Red-cappedRobin-Chat.jpg", photographer: "Marna Buys", credit: "© Peter Boesman, www.xeno-canto.org, XC280179", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Red-capped Robin-Chat contact call", afrikaans: "Nataljanfrederik kontak", hotspot: "Isimangaliso; Magoebas/Soutpans-/Waterberg; Mpumalanga; Kruger NP Pafuri", habitat: "Forest; Woodland", birdgroup: "Garden and Woodland", level: "2 Intermediate", 
audio: "gardenwoodland/XC349556_Red-cappedRobin-Chat.mp3", spectrogram: "gardenwoodland/XC349556_Red-cappedRobin-Chat.png",image: "gardenwoodland/XC349556_Red-cappedRobin-Chat.jpg", photographer: "Marna Buys", credit: "© Lisa Boocock, www.xeno-canto.org, XC349556", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Noise reduction applied"},

{english: "Eastern Nicator", afrikaans: "Geelvleknikator", hotspot: "Isimangaliso; Magoebas/Soutpans-/Waterberg; Mpumalanga; Kruger NP Pafuri", habitat: "Forest; Woodland", birdgroup: "Garden and Woodland", level: "3 Advanced", audio: "gardenwoodland/XC398160_EasternNicator.mp3", spectrogram: "gardenwoodland/XC398160_EasternNicator.png",image: "gardenwoodland/XC398160_EasternNicator.jpg", photographer: "Marna Buys", credit: "© Peter Boesman, www.xeno-canto.org, XC398160", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Olive Bushshrike", afrikaans: "Olyfboslaksman", hotspot: "General", habitat: "Forest; Woodland", birdgroup: "Garden and Woodland", level: "2 Intermediate", 
audio: "gardenwoodland/XC779397_OliveBushshrike.mp3", spectrogram: "gardenwoodland/XC779397_OliveBushshrike.png",image: "gardenwoodland/XC779397_OliveBushshrike.jpg", photographer: "Marna Buys", credit: "© Rick Nuttall, www.xeno-canto.org, XC779397", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Coppery-tailed Coucal", afrikaans: "Grootvleiloerie", hotspot: "Caprivi/Chobe", habitat: "Wetland", birdgroup: "Garden and Woodland", level: "1 Beginner", 
audio: "gardenwoodland/XC854393_Coppery-tailedCoucal.mp3", spectrogram: "gardenwoodland/XC854393_Coppery-tailedCoucal.png",image: "gardenwoodland/XC854393_Coppery-tailedCoucal.jpg", photographer: "Marna Buys", credit: "© Dries Van de Loock, www.xeno-canto.org, XC854393", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Senegal Coucal", afrikaans: "Senegalvleiloerie", hotspot: "Caprivi/Chobe; Kruger NP Pafuri", habitat: "Grassland; Scrub", birdgroup: "Garden and Woodland", level: "2 Intermediate", 
audio: "gardenwoodland/XC819110_SenegalCoucal.mp3", spectrogram: "gardenwoodland/XC819110_SenegalCoucal.png",image: "gardenwoodland/XC819110_SenegalCoucal.jpg", photographer: "Marna Buys", credit: "© Rick Nuttall, www.xeno-canto.org, XC819110", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Bradfield's Hornbill", afrikaans: "Bradfieldneushoringvoël", hotspot: "Caprivi/Chobe", habitat: "Woodland", birdgroup: "Garden and Woodland", level: "2 Intermediate", audio: "gardenwoodland/XC346862_BradfieldsHornbill.mp3", spectrogram: "gardenwoodland/XC346862_BradfieldsHornbill.png",image: "gardenwoodland/XC346862_BradfieldsHornbill.jpg", photographer: "Marna Buys", credit: "© Peter Boesman, www.xeno-canto.org, XC346862", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Swamp Boubou", afrikaans: "Moeraswaterfiskaal", hotspot: "Caprivi/Chobe", habitat: "Forest; Woodland; Mangrove", birdgroup: "Garden and Woodland", level: "3 Advanced", audio: "gardenwoodland/XC346835_SwampBoubou.mp3", spectrogram: "gardenwoodland/XC346835_SwampBoubou.png",image: "gardenwoodland/XC346835_SwampBoubou.jpg", photographer: "Marna Buys", credit: "© Peter Boesman, www.xeno-canto.org, XC346835", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Hartlaub's Babbler", afrikaans: "Witkruiskatlagter", hotspot: "Caprivi/Chobe", habitat: "Scrub; Forest; Woodland", birdgroup: "Garden and Woodland", level: "2 Intermediate", audio: "gardenwoodland/XC347141_HartlaubsBabbler.mp3", spectrogram: "gardenwoodland/XC347141_HartlaubsBabbler.png",image: "gardenwoodland/XC347141_HartlaubsBabbler.jpg", photographer: "Marna Buys", credit: "© Peter Boesman, www.xeno-canto.org, XC347141", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Black-faced Babbler", afrikaans: "Swartwangkatlagter", hotspot: "Caprivi/Chobe", habitat: "Savanna", birdgroup: "Garden and Woodland", level: "2 Intermediate", audio: "gardenwoodland/XC189023_Black-facedBabbler.mp3", spectrogram: "gardenwoodland/XC189023_Black-facedBabbler.png",image: "gardenwoodland/XC189023_Black-facedBabbler.jpg", photographer: "Marna Buys", credit: "© Niall Perrins, www.xeno-canto.org, XC189023", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Souza's Shrike", afrikaans: "Souzalaksman", hotspot: "Caprivi/Chobe", habitat: "Woodland", birdgroup: "Garden and Woodland", level: "3 Advanced", audio: "gardenwoodland/XC398104_SouzasShrike.mp3", spectrogram: "gardenwoodland/XC398104_SouzasShrike.png",image: "gardenwoodland/XC398104_SouzasShrike.jpg", photographer: "Marna Buys", credit: "© Peter Boesman, www.xeno-canto.org, XC398104", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Sharp-tailed Starling", afrikaans: "Spitsstertglansspreeu", hotspot: "Caprivi/Chobe", habitat: "Woodland", birdgroup: "Garden and Woodland", level: "3 Advanced", audio: "gardenwoodland/XC508959_Sharp-tailedStarling.mp3", spectrogram: "gardenwoodland/XC508959_Sharp-tailedStarling.png",image: "gardenwoodland/XC508959_Sharp-tailedStarling.jpg", photographer: "Marna Buys", credit: "© Peter Boesman, www.xeno-canto.org, XC508959", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Schalow's Turaco", afrikaans: "Langkuifloerie", hotspot: "Caprivi/Chobe", habitat: "Forest; Woodland", birdgroup: "Garden and Woodland", level: "1 Beginner", audio: "gardenwoodland/XC1004439_SchalowsTuraco.mp3", spectrogram: "gardenwoodland/XC1004439_SchalowsTuraco.png",image: "gardenwoodland/XC1004439_SchalowsTuraco.jpg", photographer: "Marna Buys", credit: "© Marc Anderson, www.xeno-canto.org, XC1004439", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Pale-throated Greenbul", afrikaans: "Geelkeelwillie", hotspot: "Caprivi/Chobe", habitat: "Forest; Woodland; Scrub", birdgroup: "Garden and Woodland", level: "3 Advanced", audio: "gardenwoodland/XC1084021_Yellow-throatedLeaflove.mp3", spectrogram: "gardenwoodland/XC1084021_Yellow-throatedLeaflove.png",image: "gardenwoodland/XC1084021_Yellow-throatedLeaflove.jpg", photographer: "Marna Buys", credit: "© Bram Piot, www.xeno-canto.org, XC1084021", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Tropical Boubou", afrikaans: "Tropiese waterfiskaal", hotspot: "Caprivi/Chobe; Kruger NP Pafuri", habitat: "Forest; Woodland; Garden", birdgroup: "Garden and Woodland", level: "3 Advanced", audio: "gardenwoodland/XC878241_TropicalBoubou.mp3", spectrogram: "gardenwoodland/XC878241_TropicalBoubou.png",image: "gardenwoodland/XC878241_TropicalBoubou.jpg", photographer: "Marna Buys", credit: "© Marc Anderson, www.xeno-canto.org, XC878241", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Collared Palm Thrush", afrikaans: "Palmmôrelyster", hotspot: "Caprivi/Chobe; Kruger NP Pafuri", habitat: "Thickets; Palm Savanna", birdgroup: "Garden and Woodland", level: "3 Advanced", audio: "gardenwoordland/XC365252_CollaredPalmThrush.mp3", spectrogram: "gardenwoordland/XC365252_CollaredPalmThrush.png",image: "gardenwoordland/XC365252_CollaredPalmThrush.jpg", photographer: "Marna Buys", credit: "© Frank Lambert, www.xeno-canto.org, XC365252", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Chorister Robin-Chat", afrikaans: "Lawaaimakerjanfrederik", hotspot: "Magoebas/Soutpans-/Waterberg", habitat: "Forest", birdgroup: "Garden and Woodland", level: "3 Advanced", audio: "gardenwoodland/XC446697_ChoristerRobin-Chat.mp3", spectrogram: "gardenwoodland/XC446697_ChoristerRobin-Chat.png",image: "gardenwoodland/XC446697_ChoristerRobin-Chat.jpg", photographer: "Marna Buys", credit: "© Tim Cockrcroft, www.xeno-canto.org, XC446697", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Drakensberg Rockjumber", afrikaans: "Oranjeborsberglyster", hotspot: "Drakensberg & Sani Pass", habitat: "Grassland; Rocky area; Mountain", birdgroup: "Garden and Woodland", level: "3 Advanced", audio: "gardenwoodland/XC341265_DrakensbergRockjumper.mp3", spectrogram: "gardenwoodland/XC341265_DrakensbergRockjumper.png",image: "gardenwoodland/XC341265_DrakensbergRockjumper.jpg", photographer: "Marna Buys", credit: "© Lynette Rudman, www.xeno-canto.org, XC341265", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Bush Blackcap", afrikaans: "Rooibektiptol", hotspot: "Drakensberg & Sani Pass", habitat: "Forest", birdgroup: "Garden and Woodland", level: "3 Advanced", audio: "gardenwoodlandXC459480_BushBlackcap.mp3", spectrogram: "gardenwoodlandXC459480_BushBlackcap.png",image: "gardenwoodlandXC459480_BushBlackcap.jpg", photographer: "Marna Buys", credit: "© Rafael Nussbaumer, www.xeno-canto.org, XC459480", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Buff-streaked Chat", afrikaans: "Bergklipwagter", hotspot: "Drakensberg & Sani Pass", habitat: "Grassland; Rocky area", birdgroup: "Garden and Woodland", level: "3 Advanced", audio: "gardenwoodland/XC517512_Buff-streakedChat.mp3", spectrogram: "gardenwoodland/XC517512_Buff-streakedChat.png",image: "gardenwoodland/XC517512_Buff-streakedChat.jpg", photographer: "Marna Buys", credit: "© Frank Lambert, www.xeno-canto.org, XC517512", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Brown-hooded Kingfisher", afrikaans: "Bruinkopvisvanger", hotspot: "General", habitat: "Woodland; Forest; Garden", birdgroup: "Garden and Woodland", level: "1 Beginner", 
audio: "gardenwoodland/XC1103069_Brown-hoodedKingfisher.mp3", spectrogram: "gardenwoodland/XC1103069_Brown-hoodedKingfisher.png",image: "gardenwoodland/XC1103069_Brown-hoodedKingfisher.jpg", photographer: "Marna Buys", credit: "© Marna Buys, www.xeno-canto.org, XC1103069", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Grey-headed Kingfisher", afrikaans: "Gryskopvisvanger", hotspot: "Wider Gauteng 100km/Nylsvley; Kruger National Park", habitat: "Woodland", birdgroup: "Garden and Woodland", level: "2 Intermediate", 
audio: "gardenwoodland/XC758769_Grey-headedKingfisher.mp3", spectrogram: "gardenwoodland/XC758769_Grey-headedKingfisher.png",image: "gardenwoodland/XC758769_Grey-headedKingfisher.jpg", photographer: "Marna Buys", credit: "© Nature sounds by Simply Birding, www.xeno-canto.org, XC758769", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Striped Kingfisher", afrikaans: "Gestreepte Visvanger", hotspot: "General", habitat: "Woodland; Savanna", birdgroup: "Garden and Woodland", level: "2 Intermediate", 
audio: "gardenwoodland/XC266879_StripedKingfisher.mp3", spectrogram: "gardenwoodland/XC266879_StripedKingfisher.png",image: "gardenwoodland/XC266879_StripedKingfisher.jpg", photographer: "Marna Buys", credit: "© Andrew Spencer, www.xeno-canto.org, XC266879", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Woodland Kingfisher 2 birds interacting", afrikaans: "Bosveldvisvanger 2 voëls interaksie", hotspot: "General", habitat: "Woodland; Forest", birdgroup: "Garden and Woodland", level: "1 Beginner", audio: "gardenwoodland/XC268610_WoodlandKingfisher.mp3", spectrogram: "gardenwoodland/XC268610_WoodlandKingfisher.png",image: "gardenwoodland/XC268610_WoodlandKingfisher.jpg", photographer: "Marna Buys", credit: "© Andrew Spencer, www.xeno-canto.org, XC268610", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Woodland Kingfisher", afrikaans: "Bosveldvisvanger", hotspot: "General", habitat: "Woodland; Forest", birdgroup: "Garden and Woodland", level: "1 Beginner", 
audio: "gardenwoodland/XC280342_WoodlandKingfisher.mp3", spectrogram: "gardenwoodland/XC280342_WoodlandKingfisher.png",image: "gardenwoodland/XC280342_WoodlandKingfisher.jpg", photographer: "Marna Buys", credit: "© Peter Boesman, www.xeno-canto.org, XC280342, background birds: black-headed oriole, emerald-spotted wood-dove", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Woodland Kingfisher alarm call", afrikaans: "Bosveldvisvanger waarskuwingsroep", hotspot: "General", habitat: "Woodland; Forest", birdgroup: "Garden and Woodland", level: "1 Beginner", 
audio: "gardenwoodland/XC213653_WoodlandKingfisher.mp3", spectrogram: "gardenwoodland/XC213653_WoodlandKingfisher.png",image: "gardenwoodland/XC213653_WoodlandKingfisher.jpg", photographer: "Marna Buys", credit: "© Tom Wulf www.xeno-canto.org, XC213653", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Red-faced Mousebird", afrikaans: "Rooiwangmuisvoël", hotspot: "General", habitat: "Woodland; Garden", birdgroup: "Garden and Woodland", level: "1 Beginner", 
audio: "gardenwoodland/XC1071005_Red-facedMousebird.mp3", spectrogram: "gardenwoodland/XC1071005_Red-facedMousebird.png",image: "gardenwoodland/XC1071005_Red-facedMousebird.jpg", photographer: "Marna Buys", credit: "© Marc Anderson, www.xeno-canto.org, XC1071005", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Speckled Mousebird", afrikaans: "Gevlekte Muisvoël", hotspot: "General", habitat: "Savanna; Gardens", birdgroup: "Garden and Woodland", level: "2 Intermediate", 
audio: "gardenwoodland/XC1103077_SpeckledMousebird.mp3", spectrogram: "gardenwoodland/XC1103077_SpeckledMousebird.png",image: "gardenwoodland/XC1103077_SpeckledMousebird.jpg", photographer: "Marna Buys", credit: "© Marna Buys, www.xeno-canto.org, XC1103077", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Black-Collared Barbet", afrikaans: "Rooikophoutkapper", hotspot: "General", habitat: "Woodland; Garden", birdgroup: "Garden and Woodland", level: "1 Beginner", 
audio: "gardenwoodland/XC366605_Black-collaredBarbet.mp3", spectrogram: "gardenwoodland/XC366605_Black-collaredBarbet.png",image: "gardenwoodland/XC366605_Black-collaredBarbet.jpg", photographer: "Marna Buys", credit: "© Frank Lambert, www.xeno-canto.org, XC366605", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Crested Barbet", afrikaans: "Kuifkophoutkapper", hotspot: "General", habitat: "Woodland; Garden; Grassland; Savanna", birdgroup: "Garden and Woodland", level: "1 Beginner", 
audio: "gardenwoodland/XC963012_CrestedBarbet.mp3", spectrogram: "gardenwoodland/XC963012_CrestedBarbet.png",image: "gardenwoodland/XC963012_CrestedBarbet.jpg", photographer: "Marna Buys", credit: "© Dries Van de Loock, www.xeno-canto.org, XC963012", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Yellow-fronted Tinkerbird Variation of Call", afrikaans: "Geelblestinker Variasie van roep", hotspot: "General", habitat: "Savanna; Woodland; Forest; Garden", birdgroup: "Garden and Woodland", level: "1 Beginner", 
audio: "gardenwoodland/XC1103079_Yellow-frontedTinkerbird.mp3", spectrogram: "gardenwoodland/XC1103079_Yellow-frontedTinkerbird.png",image: "gardenwoodland/XC1103079_Yellow-frontedTinkerbird.jpg", photographer: "Marna Buys", credit: "© Marna Buys, www.xeno-canto.org, XC1103079", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Yellow-fronted Tinkerbird", afrikaans: "Geelblestinker", hotspot: "General", habitat: "Savanna; Woodland; Forest; Garden", birdgroup: "Garden and Woodland", level: "1 Beginner", 
audio: "gardenwoodland/XC1103080_Yellow-frontedTinkerbird.mp3", spectrogram: "gardenwoodland/XC1103080_Yellow-frontedTinkerbird.png",image: "gardenwoodland/XC1103080_Yellow-frontedTinkerbird.jpg", photographer: "Marna Buys", credit: "© Marna Buys, www.xeno-canto.org, XC1103080", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Yellow-rumped Tinkerbird", afrikaans: "Swartblestinker", hotspot: "Isimangaliso; Mpumalanga; Kruger National Park", habitat: "Forest; Woodland; Garden", birdgroup: "Garden and Woodland", level: "1 Beginner", 
audio: "gardenwoodland/XC356232_Yellow-rumpedTinkerbird.mp3", spectrogram: "gardenwoodland/XC356232_Yellow-rumpedTinkerbird.png",image: "gardenwoodland/XC356232_Yellow-rumpedTinkerbird.jpg", photographer: "Marna Buys", credit: "© Gerard Gorman, www.xeno-canto.org, XC356232", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Golden-tailed Woodpecker", afrikaans: "Goudstertspeg", hotspot: "General", habitat: "Savanna; Woodland; Garden", birdgroup: "Garden and Woodland", level: "1 Beginner", 
audio: "gardenwoodland/XC346653_Golden-tailedWoodpecker.mp3", spectrogram: "gardenwoodland/XC346653_Golden-tailedWoodpecker.png",image: "gardenwoodland/XC346653_Golden-tailedWoodpecker.jpg", photographer: "Marna Buys", credit: "© Peter Boesman, www.xeno-canto.org, XC346653", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Cardinal Woodpecker Alarm Call", afrikaans: "Kardinaalspeg Waarskuwingsroep", hotspot: "General", habitat: "Savanna; Woodland; Forest; Garden", birdgroup: "Garden and Woodland", level: "1 Beginner", 
audio: "gardenwoodland/XC424181_CardinalWoodpecker.mp3", spectrogram: "gardenwoodland/XC424181_CardinalWoodpecker.png",image: "gardenwoodland/XC424181_CardinalWoodpecker.jpg", photographer: "Marna Buys", credit: "© Tim Cockrcroft, www.xeno-canto.org, XC424181", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Cardinal Woodpecker", afrikaans: "Kardinaalspeg", hotspot: "General", habitat: "Savanna; Woodland; Forest; Garden", birdgroup: "Garden and Woodland", level: "1 Beginner", 
audio: "gardenwoodland/XC280247_CardinalWoodpecker.mp3", spectrogram: "gardenwoodland/XC280247_CardinalWoodpecker.png",image: "gardenwoodland/XC280247_CardinalWoodpecker.jpg", photographer: "Marna Buys", credit: "© Peter Boesman, www.xeno-canto.org, XC280247, background birds: cape robin-chat", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Green Wood Hoopoe", afrikaans: "Rooibekkakelaaar", hotspot: "General North; General East; General South", habitat: "Woodland; Forest; Garden", birdgroup: "Garden and Woodland", level: "1 Beginner", audio: "gardenwoodland/XC879939_GreenWoodHoopoe.mp3", spectrogram: "gardenwoodland/XC879939_GreenWoodHoopoe.png",image: "gardenwoodland/XC879939_GreenWoodHoopoe.jpg", photographer: "Marna Buys", credit: "© Marc Anderson, www.xeno-canto.org, XC879939", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "African Hoopoe", afrikaans: "Hoep-Hoep", hotspot: "General East; General Central; General North; General South; General West", habitat: "Woodland; Garden", birdgroup: "Garden and Woodland", level: "1 Beginner", audio: "gardenwoodland/XC1038410_AfricanHoopoe.mp3", spectrogram: "gardenwoodland/XC1038410_AfricanHoopoe.png",image: "gardenwoodland/XC1038410_AfricanHoopoe.jpg", photographer: "Marna Buys", credit: "© Bobby Wilcox, www.xeno-canto.org, XC1038410", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"}

  
];
