const warblers = [
  
{english: "Olive-tree Warbler", afrikaans: "Olyfboomsanger", hotspot: "Zaagkuildrift", habitat: "Bushveld", birdgroup: "Warblers", level: "3 Advanced", 
 audio: "warblers/XC819380_Olive-treeWarbler.mp3", spectrogram: "warblers/XC819380_Olive-treeWarbler.png", image: "warblers/XC819380_Olive-treeWarbler.jpg", photographer: "Marna Buys", credit: "© Rick Nuttall, www.xeno-canto.org, XC819380", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Common Whitethroat alarm call", afrikaans: "Witkeelsanger alarm call", hotspot: "Zaagkuildrift", habitat: "Bushveld", birdgroup: "Warblers", level: "3 Advanced", 
 audio: "warblers/XC521207_CommonWhitethroat.mp3", spectrogram: "warblers/XC521207_CommonWhitethroat.png", image: "warblers/XC521207_CommonWhitethroat.jpg", photographer: "Marna Buys", credit: "© Tony Archer, www.xeno-canto.org, XC521207, Alarm call, Background birds: red-faced mousebird", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Barred Wren-Warbler", afrikaans: "Gebande Sanger", hotspot: "Zaagkuildrift", habitat: "Bushveld", birdgroup: "Warblers", level: "2 Intermediate", 
 audio: "warblers/XC708257_BarredWren-Warbler.mp3", spectrogram: "warblers/XC708257_BarredWren-Warbler.png", image: "warblers/XC708257_BarredWren-Warbler.jpg", photographer: "Marna Buys", credit: "© Tony Archer, www.xeno-canto.org, XC708257", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Rudd's Apalis", afrikaans: "Ruddse Kleinjantjie", hotspot: "St Lucia", habitat: "Forest", birdgroup: "Warblers", level: "3 Advanced", 
 audio: "warblers/XC62390_RuddsApalis.mp3", spectrogram: "warblers/XC62390_RuddsApalis.png", image: "warblers/XC62390_RuddsApalis.jpg", photographer: "Marna Buys", credit: "© Charles Hesse, www.xeno-canto.org, XC62390", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/2.5/", changes: "Original recording"},
  
{english: "Marsh Warbler alarm call", afrikaans: "Europese Rietsanger alarm call", hotspot: "Zaagkuildrift", habitat: "Bushveld", birdgroup: "Warblers", level: "3 Advanced", 
audio: "warblers/XC632299_MarshWarbler.mp3", spectrogram: "warblers/XC632299_MarshWarbler.png", image: "warblers/XC632299_MarshWarbler.jpg", photographer: "Marna Buys", credit: "© Tony Archer, www.xeno-canto.org, XC632299; Alarm call", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Karoo Eremomela", afrikaans: "Groenbossanger", hotspot: "Platbakkies", habitat: "Shrubland", birdgroup: "Warblers", level: "2 Intermediate", 
audio: "warblers/XC392489_KarooEremomela.mp3", spectrogram: "warblers/XC392489_KarooEremomela.png",image: "warblers/XC392489_KarooEremomela.jpg", photographer: "Marna Buys", credit: "© Peter Boesman, www.xeno-canto.org, XC392489", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Cinnamon-breasted Warbler", afrikaans: "Kaneelborssanger", hotspot: "Platbakkies", habitat: "Rocky", birdgroup: "Warblers", level: "2 Intermediate", 
audio: "warblers/XC515440_Cinnamon-breastedWarbler.mp3", spectrogram: "warblers/XC515440_Cinnamon-breastedWarbler.png",image: "warblers/XC515440_Cinnamon-breastedWarbler.jpg", photographer: "Marna Buys", credit: "© Frank Lambert, www.xeno-canto.org, XC515440", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Layards Warbler", afrikaans: "Grystjeriktik", hotspot: "Platbakkies; Lesotho", habitat: "Shrubland; Fynbos", birdgroup: "Warblers", level: "3 Advanced", 
audio: "warblers/XC600217_LayardsWarbler.mp3", spectrogram: "warblers/XC600217_LayardsWarbler.png",image: "warblers/XC600217_LayardsWarbler.jpg", photographer: "Marna Buys", credit: "© Lynette Rudman, www.xeno-canto.org, XC600217", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Rufous-eared Warbler", afrikaans: "Rooi-oor Langstertjie", hotspot: "Platbakkies", habitat: "Shrubland", birdgroup: "Warblers", level: "3 Advanced", 
audio: "warblers/XC691414_Rufous-earedWarbler.mp3", spectrogram: "warblers/XC691414_Rufous-earedWarbler.png",image: "warblers/XC691414_Rufous-earedWarbler.jpg", photographer: "Marna Buys", credit: "© Lynette Rudman, www.xeno-canto.org, XC691414", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Lesser Swamp Warbler", afrikaans: "Kaapse Rietsanger", hotspot: "General", habitat: "Wetland; Reedbeds", birdgroup: "Warblers", level: "2 Intermediate", audio: "warblers/XC1034456_LesserSwampWarbler.mp3", spectrogram: "warblers/XC1034456_LesserSwampWarbler.png",image: "warblers/XC1034456_LesserSwampWarbler.jpg", photographer: "Marna Buys", credit: "© Nature sounds by Simply Birding, www.xeno-canto.org, XC1034456", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Little Rush Warbler", afrikaans: "Kaapse Vleisanger", hotspot: "General", habitat: "Wetland; Reedbeds", birdgroup: "Warblers", level: "1 Beginner", audio: "warblers/XC252088_LittleRushWarbler.mp3", spectrogram: "warblers/XC252088_LittleRushWarbler.png",image: "warblers/XC252088_LittleRushWarbler.jpg", photographer: "Marna Buys", credit: "© Lynette Rudman, www.xeno-canto.org, XC252088", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "African Reed Warbler", afrikaans: "Kleinrietsanger", hotspot: "General", habitat: "Reedbeds", birdgroup: "Warblers", level: "2 Intermediate", audio: "warblers/XC386560_AfricanReedWarbler.mp3", spectrogram: "warblers/XC386560_AfricanReedWarbler.png",image: "warblers/XC386560_AfricanReedWarbler.jpg", photographer: "Marna Buys", credit: "© Tim Cockrcroft, www.xeno-canto.org, XC386560", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Great Reed Warbler", afrikaans: "Grootrietsanger", hotspot: "Wider Gauteng 100km/Nylsvley; Kruger National Park; Isimangaliso", habitat: "Savanna; Reedbeds", birdgroup: "Warblers", level: "2 Intermediate", audio: "warblers/XC279760_GreatReedWarbler.mp3", spectrogram: "warblers/XC279760_GreatReedWarbler.png",image: "warblers/XC279760_GreatReedWarbler.jpg", photographer: "Marna Buys", credit: "© Peter Boesman, www.xeno-canto.org, XC279760", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Sedge Warbler", afrikaans: "Europese Vleisanger", hotspot: "Wider Gauteng 100km/Nylsvley", habitat: "Wetland", birdgroup: "Warblers", level: "3 Advanced", audio: "warblers/XC305382_SedgeWarbler.mp3", spectrogram: "warblers/XC305382_SedgeWarbler.png",image: "warblers/XC305382_SedgeWarbler.jpg", photographer: "Marna Buys", credit: "© Tim Cockrcroft, www.xeno-canto.org, XC305382", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Icterine Warbler Alarm Call", afrikaans: "Spotsanger Alarm", hotspot: "Wider Gauteng 100km/Nylsvley; Kruger National Park; Magoebas/Soutpans-/Waterberg", habitat: "Forest; Garden; Woodland", birdgroup: "Warblers", level: "3 Advanced", audio: "warblers/XC521214_IcterineWarbler.mp3", spectrogram: "warblers/XC521214_IcterineWarbler.png",image: "warblers/XC521214_IcterineWarbler.jpg", photographer: "Marna Buys", credit: "© Tony Archer, www.xeno-canto.org, XC521214", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Icterine Warbler", afrikaans: "Spotsanger", hotspot: "Wider Gauteng 100km/Nylsvley; Kruger National Park; Magoebas/Soutpans-/Waterberg", habitat: "Forest; Garden; Woodland", birdgroup: "Warblers", level: "3 Advanced", audio: "warblers/XC459224_IcterineWarbler.mp3", spectrogram: "warblers/XC459224_IcterineWarbler.png",image: "warblers/XC459224_IcterineWarbler.jpg", photographer: "Marna Buys", credit: "© Lynette Rudman, www.xeno-canto.org, XC459224", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Barratt's Warbler Alarm Call", afrikaans: "Ruigtesanger Alarm", hotspot: "Drakensberg & Sani Pass; Mpumalanga; Magoebas/Soutpans-/Waterberg; Eastern Cape", habitat: "Forest; Scrub", birdgroup: "Warblers", level: "2 Intermediate", audio: "warblers/XC374559_BarrattsWarbler.mp3", spectrogram: "warblers/XC374559_BarrattsWarbler.png",image: "warblers/XC374559_BarrattsWarbler.jpg", photographer: "Marna Buys", credit: "© Tim Cockrcroft, www.xeno-canto.org, XC374559", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Barratt's Warbler", afrikaans: "Ruigtesanger", hotspot: "Drakensberg & Sani Pass; Mpumalanga; Magoebas/Soutpans-/Waterberg; Eastern Cape", habitat: "Forest; Scrub", birdgroup: "Warblers", level: "2 Intermediate", audio: "warblers/XC522623_BarrattsWarbler.mp3", spectrogram: "warblers/XC522623_BarrattsWarbler.png",image: "warblers/XC522623_BarrattsWarbler.jpg", photographer: "Marna Buys", credit: "© Lynette Rudman, www.xeno-canto.org, XC522623", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Knysna Warbler", afrikaans: "Knysnaruigtesanger", hotspot: "Garden Route; Eastern Cape", habitat: "Forest", birdgroup: "Warblers", level: "2 Intermediate", audio: "warblers/XC1103772_KnysnaWarbler.mp3", spectrogram: "warblers/XC1103772_KnysnaWarbler.png",image: "warblers/XC1103772_KnysnaWarbler.jpg", photographer: "Marna Buys", credit: "© Marna Buys, www.xeno-canto.org, XC1103772", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Fan-tailed Grassbird", afrikaans: "Breëstertsanger", hotspot: "Drakensberg & Sani Pass; Eastern Cape; Mpumalanga", habitat: "Grassland", birdgroup: "Warblers", level: "3 Advanced", audio: "warblers/XC449663_Fan-tailedGrassbird.mp3", spectrogram: "warblers/XC449663_Fan-tailedGrassbird.png",image: "warblers/XC449663_Fan-tailedGrassbird.jpg", photographer: "Marna Buys", credit: "© Murray Christian, www.xeno-canto.org, XC449663", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Yellow-throated Woodland Warbler", afrikaans: "Geelkeelsanger", hotspot: "Drakensberg & Sani Pass; Eastern Cape; Mpumalanga; Magoebas/Soutpans-/Waterberg; Garden Route", habitat: "Forest", birdgroup: "Warblers", level: "3 Advanced", audio: "warblers/XC280555_Yellow-throatedWoodlandWarbler.mp3", spectrogram: "warblers/XC280555_Yellow-throatedWoodlandWarbler.png",image: "warblers/XC280555_Yellow-throatedWoodlandWarbler.jpg", photographer: "Marna Buys", credit: "© Peter Boesman, www.xeno-canto.org, XC280555", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "Willow Warbler Contact Call", afrikaans: "Hofsanger Kontak", hotspot: "Wider Gauteng 100km/Nylsvley; Kruger National Park; Magoebas/Soutpans-/Waterberg; East London; Drakensberg & Sani Pass", habitat: "Woodland; Forest", birdgroup: "Warblers", level: "2 Intermediate", audio: "warblers/XC444788_WillowWarbler.mp3", spectrogram: "warblers/XC444788_WillowWarbler.png",image: "warblers/XC444788_WillowWarbler.jpg", photographer: "Marna Buys", credit: "© Tim Cockrcroft, www.xeno-canto.org, XC444788", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Willow Warbler", afrikaans: "Hofsanger", hotspot: "Wider Gauteng 100km/Nylsvley; Kruger National Park; Magoebas/Soutpans-/Waterberg; East London; Drakensberg & Sani Pass", habitat: "Woodland; Forest", birdgroup: "Warblers", level: "1 Beginner", audio: "warblers/XC761163_WillowWarbler.mp3", spectrogram: "warblers/XC761163_WillowWarbler.png",image: "warblers/XC761163_WillowWarbler.jpg", photographer: "Marna Buys", credit: "© Lynette Rudman, www.xeno-canto.org, XC761163", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "African Yellow Warbler", afrikaans: "Geelsanger", hotspot: "Drakensberg & Sani Pass; Mpumalanga; Wider Gauteng 100km/Nylsvley; Magoebas/Soutpans-/Waterberg", habitat: "Scrub; Wetland", birdgroup: "Warblers", level: "3 Advanced", audio: "warblers/XC280360_AfricanYellowWarbler.mp3", spectrogram: "warblers/XC280360_AfricanYellowWarbler.png",image: "warblers/XC280360_AfricanYellowWarbler.jpg", photographer: "Marna Buys", credit: "© Peter Boesman, www.xeno-canto.org, XC280360", licenseLink: "https://creativecommons.org/licenses/by-nc-nd/4.0/", changes: "Original recording"},

{english: "River Warbler", afrikaans: "Sprinkaansanger", hotspot: "Wider Gauteng 100km/Nylsvley; Kruger NP Pafuri", habitat: "Woodland", birdgroup: "Warblers", level: "2 Intermediate", audio: "warblers/XC711881_RiverWarbler.mp3", spectrogram: "warblers/XC711881_RiverWarbler.png",image: "warblers/XC711881_RiverWarbler.jpg", photographer: "Marna Buys", credit: "© Marna Buys, www.xeno-canto.org, XC711881", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"},

{english: "Victorin's Warbler", afrikaans: "Rooiborsruigtesanger", hotspot: "Western Cape; Garden Route", habitat: "Fynbos", birdgroup: "Warblers", level: "3 Advanced", audio: "warblers/XC1028320_VictorinsWarbler.mp3", spectrogram: "warblers/XC1028320_VictorinsWarbler.pmg",image: "warblers/XC1028320_VictorinsWarbler.jpg", photographer: "Marna Buys", credit: "© Tristan Spurway, www.xeno-canto.org, XC1028320", licenseLink: "https://creativecommons.org/licenses/by-nc-sa/4.0/", changes: "Original recording"}

  
];
